# 신경망의 입력값과 가중치
* 신경망에 입력되는 값은 여러 개이다.
* 입력값에 해당하는 가중치도 여러 개.
  * 1층의 첫 번째 뉴런에 대한 선형 조합 계산 : $z^{(1)}_{1} = w^{(1)}_{11}x_1 + w^{(1)}_{12}x_2+b^{(1)}_1$

In [3]:
import numpy as np

X = np.array([[1, 2]])

# 2개의 입력을 받는 3개의 뉴런
W = np.array([[1, 2, 3],
              [4, 5, 6]])

X.shape, W.shape

((1, 2), (2, 3))

In [4]:
Z = X @ W
Z

array([[ 9, 12, 15]])

In [5]:
B = np.array([10, 11, 12])

Z = X @ W + B
Z

array([[19, 23, 27]])

# 단순한 3층 신경망 구성하기
* 1층을 구성하는 표기
 * 1층의 1번째 뉴런만 표기 : $z_1^{(1)} = w_{11}^{(1)}x_1 + w_{12}^{(1)}x_2+b_1^{(1)}$
 * 1층 전체를 나타내기 : $Z^{(1)} = XW^{(1)} + B^{(1)}$
   * B의 원소 수는 뉴런의 개수와 같다.
 * $X = (x_1, x_2)$
 * $W^{(1)} = \begin{pmatrix}w_{11}^{(1)} & w_{21}^{(1)} & w_{31}^{(1)} \\ w_{12}^{(1)} & w_{22}^{(1)} & w_{32}^{(1)}
 \end{pmatrix}$
 * $B^{(1)} = \begin{pmatrix}b_1^{(1)}&b_2^{(1)}&b_3^{(1)}\end{pmatrix}$
 * $Z^{(1)} = \begin{pmatrix}z_1^{(1)}&z_2^{(1)}&z_3^{(1)}\end{pmatrix}$

In [6]:
# 시그모이드 함수 - 은닉층에서 사용할 것.
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# 항등 함수 구현(identity function) - 출력층에서 사용할 것.
def identity_function(x):
  return x

In [8]:
X = np.array([1.0, 0.5])

W1 = np.array([[0.1, 0.3, 0.5],
               [0.2, 0.4, 0.6]])

B1 = np.array([0.1, 0.2, 0.3])

Z1 = X @ W1 + B1 # 1층의 선형 연산의 결과
A1 = sigmoid(Z1) # 활성화 함수 적용으로 각 뉴런의 결과물에 비선형성 부여
A1

array([0.57444252, 0.66818777, 0.75026011])

In [9]:
# 두 번째 층 구현
W2 = np.array([[0.1, 0.4],
               [0.2, 0.5],
               [0.3, 0.6]])

B2 = np.array([0.1, 0.2])

# 첫 번째 층의 출력값 A1이 두 번째 층의 입력 값이 된다.
Z2 = A1 @ W2 + B2
A2 = sigmoid(Z2)

A2

array([0.62624937, 0.7710107 ])

In [10]:
# 3층 출력층 구현( 활성화 함수를 항등함수 )
W3 = np.array([[0.1, 0.3],
               [0.2, 0.4]])

B3 = np.array([0.1, 0.2])

Z3 = A2 @ W3 + B3

# 예측 값
y_pred = identity_function(Z3)
y_pred

array([0.31682708, 0.69627909])

In [11]:
# 네트워크 초기화
#  네트워크가 최초로 가지고 있어야 할 가중와 편향을 설정
#  보통은 정규분포 랜덤으로 초기화 하거나, 카이밍 허, 사비에르 초깃값 등을 활용
def init_network():
  network = {}

  # 1층 매개변수 초기화
  network["W1"] = np.array([[0.1, 0.3, 0.5],
                            [0.2, 0.4, 0.6]])
  network["B1"] = np.array([0.1, 0.2, 0.3])

  # 2층 매개변수 초기화
  network["W2"] = np.array([[0.1, 0.4],
                            [0.2, 0.5],
                            [0.3, 0.6]])
  network["B2"] = np.array([0.1, 0.2])

  # 3층 매개변수 초기화
  network["W3"] = np.array([[0.1, 0.3],
                            [0.2, 0.4]])
  network["B3"] = np.array([0.1, 0.2])

  return network

# 순전파 XW+B
def forward(network, x):
  # 가중치, 편향 꺼내기
  W1, W2, W3 = network["W1"], network["W2"], network["W3"]
  b1, b2, b3 = network["B1"], network["B2"], network["B3"]

  # 1층 계산
  Z1 = (x @ W1) + b1
  A1 = sigmoid(Z1)

  # 2층 계산
  Z2 = A1 @ W2 + b2
  A2 = sigmoid(Z2)

  # 3층 계산
  Z3 = A2 @ W3 + b3
  y = identity_function(Z3)

  return y

In [12]:
model = init_network() # 모든 층의 가중치와 편향을 초기화

x = np.array([1.0, 0.5])
y = forward(model, x)

y

array([0.31682708, 0.69627909])